server:
  port: 8100

spring:
  security:
    user:
      name : user
      password : bbd6597c-bff3-48be-baa9-c646253d823b
zuul:
  routes:
    admin:
      url: http://localhost:8081
    Auth:
      url: http://localhost:8080
    project:
      url: http://localhost:8082
    user:
      url: http://localhost:8083
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 5000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
